services:
  service_a:
    build: ./service_a
    ports:
      - "8000:8000"   # REST Port
      - "50051:50051" # gRPC Port

  service_b:
    build: ./service_b
    ports:
      - "8001:8001"
    depends_on:
      - service_a

  service_c:
    build: ./service_c
    ports:
      - "8002:8002"
    depends_on:
      - service_a 
#เมื่อร RUN docker-composeแล้วสามารถเข้าถึง service ได้ด้วย localhost ดังกล่าวได้
#http://service_b:8000/user/1
#http://service_b:8001/user/1
#http://service_b:8002/user/1
